#!/bin/bash
getHelp(){
echo -e "===========\e[7mINSTRUCTION\e[27m=========="
echo "1.To use calculator do next"
echo "./script.sh calc (sub|sum|mul|div) num1 num2"
echo "2.To rewrite file to another one, but reversed do next:"
echo "./script.sh reverse file1 file2"
echo "3.To use search for word in directories do next:"
echo "./script.sh search directory string"
echo "4.To find length of string do next:"
echo "./script.sh strlen string"
echo "5.To get logs do next:"
echo "./script.sh log"
echo "6.To use interactive mode do next"
echo "./script.sh interactive"
echo "7.To exit program"
echo "./script.sh exit"
echo "You can get help any time by using './script.sh help'"
echo -e "========\e[7mEXIT CODES\e[27m========"
echo "-1 - Wrong arguments(int instead of strings and etc."
echo "-2 - Wrong action tried"
echo "-3 - File problem(no permission)"
echo "-4 - File problem(can't rewrite file"
echo "-5 - Operation error(Division by zero)"
echo "-6 - Unreadable file"
}
